### PR TITLE
Image Enhancement using GFPGAN

### PR DESCRIPTION
**Pull request by aditi-dey29**
Added an algorithm to used a pretrained GFPGAN model to enhance images containing human faces.
This is my submission for Hactoberfest.

### CODE REVIEW

**Comment by aditi-dey29** [comment]
Umm, for some reason this didn't get accepted in the hactoberfest. Could you please add the label again? I'll be grateful.

**Comment by cclauss** [comment]
@dhruvmanila What do we need to do `TheAlgorithms/Jupyter` to make this automatic?

**Comment by dhruvmanila** [comment]
@aditi-dey29 Could you provide some more details? What's it showing on the dashboard of Hacktoberfest?

**Comment by aditi-dey29** [comment]
I guess it is now in the 7 day reviewing period. Might have been some glitch.
Sorry for late reply, diwali celebrations were going on here.
Happy Diwali!

**Pull request merged**
