### PR TITLE
GAN-Pytorch Added

### PR DESCRIPTION
**Pull request by chetanpandey1266**
A simple implementation of DCGAN in Pytorch

### CODE REVIEW

**Comment by chetanpandey1266** [comment]
Just don't go with the title. I had first added GAN only but later made a commit for Unet also, so that's why had the same title and descripton as before

**Comment by hritik5102** [comment]
> Just don't go with the title. I had first added GAN only but later made a commit for Unet also, so that's why had the same title and descripton as before

**Comment by hritik5102** [comment]
> > Just don't go with the title. I had first added GAN only but later made a commit for Unet also, so that's why had the same title and descripton as before

Great work but your PR has some conflict, please resolve that conflict or else create a new issue and make a new PR (add your algorithm there) and also please mention issue #XX which you are solving. 

it would be great if you add some **documentation** of your code and some reference links.
Thank you :)

**Comment by chetanpandey1266** [comment]
Ok I will be creating a new PR keeping all the points you mentioned above

**Pull request closed without merging**
