### PR TITLE
TrapezoidalRule algorithm

### PR DESCRIPTION
**Pull request by kunyaw12**
This is a sample TrapezoidalRule algorithm

### CODE REVIEW

**Comment by kunyaw12** [comment]
this is a simple TrapezoidalRule algorithm

**Comment by hritik5102** [comment]
Hello @kunyaw12 could you please change the language from `C++` to `python`.

**Comment by kunyaw12** [comment]
@hritik5102  okay , wait a while

**Comment by kunyaw12** [comment]
@hritik5102 done

**Comment by hritik5102** [comment]
sorry, @kunyaw12  I'm closing this for now.  you will have to create a separate issue for this and then make new PR.

**Pull request closed without merging**
