### PR TITLE
Added Qlearning

### PR DESCRIPTION
**Pull request by AryanRaj315**

### CODE REVIEW

**Comment by AryanRaj315** [comment]
Hey can anyone please review this Pull Request?
Thank you!

**Review by nikhilkala — CHANGES_REQUESTED** [review]
Jupyter Notebook allows wonderful visualization so please run the cells when pushing also in this notebook the functions are not being used so try to display the results at the end as well.

> Hey can anyone please review this Pull Request?
> Thank you!

**Comment by cclauss** [comment]
> please run the cells when pushing

What does that do to file size and repo clone size?  Launching in Bundler (see README.md) might be a better approach.

**Comment by nikhilkala** [comment]
> What does that do to file size and repo clone size?

It does increase significantly if image dataset is present, but this code is working on text data so should be an increase of ~10 Kbs.
I am not aware of Bundler with Jupyter, so will look into it for future PRs.

**Pull request merged**
